name: Atualizar Estatísticas README

on:
  schedule:
    - cron: '0 0 * * *'  # executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes
